name: Deploy After Test
on:
  workflow_run:
    workflows:
      - Run Tests
    types:
      - completed
  jobs:
    deploy:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success'}}
      
      steps:
        - name: Deploy Applocation
          run: |
            echo "Test Passes"
            echo "Deploying Application..."
