name: Reusable Build and Test

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string

      run_tests:
        required: false
        default: true
        type: boolean

    outputs:
      test_result:
        description: Test result
        value: ${{ jobs.build-test.outputs.test_result }}

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    outputs:
      test_result: ${{ steps.result.outputs.test_result }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}

      - name: Build Project
        working-directory: ./uberApp/uberApp
        run: ./mvnw clean compile

      - name: Start PostgreSQL
        if: ${{ inputs.run_tests }}
        working-directory: ./uberApp/uberApp
        run: docker compose up -d postgres

      - name: Wait for PostgreSQL
        if: ${{ inputs.run_tests }}
        working-directory: ./uberApp/uberApp
        shell: bash
        run: |
          echo "Waiting for PostgreSQL..."

          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' uber-postgres 2>/dev/null || echo "starting")

            echo "PostgreSQL status: $STATUS"

            if [ "$STATUS" = "healthy" ]; then
              echo "PostgreSQL is ready."
              exit 0
            fi

            sleep 2
          done

          echo "PostgreSQL did not become healthy."
          docker compose logs postgres
          exit 1

      - name: Run Tests
        if: ${{ inputs.run_tests }}
        working-directory: ./uberApp/uberApp
        env:
         DB_URL: jdbc:postgresql://localhost:5432/uber_db
         DB_USERNAME: postgres
         DB_PASSWORD: postgres
        run: ./mvnw test 

      - name: Set Test Result
        id: result
        run: |
          echo "test_result=passed" >> "$GITHUB_OUTPUT"

      - name: Stop PostgreSQL
        if: always()
        working-directory: ./uberApp/uberApp
        run: docker compose down
