name: Run Python Test

on:
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Run Script
        run: python hello.py
